/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NhLogin: typeof import('./src/components/nhLogin.vue')['default']
    NhMain: typeof import('./src/components/nhMain.vue')['default']
    NotFound: typeof import('./src/components/notFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
